### ISSUE TITLE
422 Error when attempting to use Mistral API with Rails

### ISSUE THREAD

**Issue by arigatodon** [fsndzomga/mistral_rb#2]
Description:

I'm encountering a 500 Internal Server Error when trying to use the Mistral API in my Rails application. Specifically, this occurs when I attempt to send a chat completion creation request to the Mistral API.

Steps to Reproduce:

    I set up my Rails application to use the Mistral API following the Mistral_Rb documentation.

    I added an option for users to choose between Mistral and ChatGPT models in my search form.

    When a user submits a search with the Mistral model selected, my searches controller attempts to send a request to the Mistral API using the following code:

    client.create_chat_completion(
      model: selected_model,
      messages: [{ role: "user", content: @search.content }]
    )

    Instead of a successful response, I receive a 500 Internal Server Error with the following stack trace:

    RuntimeError (API Error: 422 - {"object":"error","message":{"detail":[{"type":"extra_forbidden","loc":["body","safe_mode"],"msg":"Extra inputs are not permitted","input":false,"url":"https://errors.pydantic.dev/2.6/v/extra_forbidden"}]},"type":"invalid_request_error","param":null,"code":null}):

    app/controllers/searches_controller.rb:52:in `create'

Setup:

    Ruby version: 3.2.2
    Rails version: 7.1.2

**Comment by fsndzomga** [comment]
Hello. I wasn't able to reproduce this error. Seems to have been an error on the Mistral AI side and it is resolved now.
Let me know if you still have that issue.
